dist: trusty

language: node_js

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.403.sh
  - chmod +x linux-install-1.10.0.403.sh
  - sudo ./linux-install-1.10.0.403.sh

script:
  - if [[ $CANARY_CLOJURESCRIPT_REPO && ${CANARY_CLOJURESCRIPT_REPO-x} ]]; then DEPS="{:deps {org.clojure/clojurescript {:git/url \"${CANARY_CLOJURESCRIPT_REPO}\" :sha \"${CANARY_CLOJURESCRIPT_REV}\"}}}"; fi
  - clojure -Sdeps "${DEPS:-{}}" -A:test
